---

# TODO Skip already installed(because slowly).
#
# TODO markdown editor
# TODO stepcounter
# TODO Lombok

- name: eclipse | Install Marketplace Client
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://download.eclipse.org/releases/mars \
  -installIU org.eclipse.epp.mpc.feature.group \
  "

- name: eclipse | Install Maven Integration for Eclipse(m2e)
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://download.eclipse.org/technology/m2e/releases,http://download.eclipse.org/releases/mars \
  -installIU org.eclipse.m2e.feature.feature.group \
  -installIU org.eclipse.m2e.logback.feature.feature.group \
  "

- name: eclipse | Install EclEmma Java Code Coverage(jacoco)
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://update.eclemma.org/ \
  -installIU com.mountainminds.eclemma.feature.feature.group \
  "

- name: eclipse | Install Eclipse CheckStyle Plugin
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://eclipse-cs.sf.net/update \
  -installIU net.sf.eclipsecs.feature.group \
  -installIU com.github.sevntu.checkstyle.checks.feature.feature.group \
  "

- name: eclipse | Install Eclipse Metrics Plugin(frank sauer)
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://metrics.sourceforge.net/update \
  -installIU net.sourceforge.metrics.feature.group \
  "

- name: eclipse | Install EGit
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://download.eclipse.org/egit/updates,http://download.eclipse.org/releases/mars \
  -installIU org.eclipse.egit.feature.group \
  -installIU org.eclipse.egit.source.feature.group \
  -installIU org.eclipse.egit.mylyn.feature.group \
  "

- name: eclipse | Install Java Decompiler Eclipse Plug-in | required Microsoft Visual C++ 2008 SP1 Redistributable Package
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://jd.benow.ca/jd-eclipse/update \
  -installIU jd.ide.eclipse.feature.feature.group \
  "

- name: eclipse | Install Quick JUnit
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://quick-junit.sourceforge.jp/updates/current/ \
  -installIU junit.extensions.eclipse.quick.feature.feature.group \
  "

# - name: eclipse | Install ShellEd
#   command: "eclipse -nosplash \
#   -application org.eclipse.equinox.p2.director \
#   -repository http://sourceforge.net/projects/shelled/files/shelled/update,http://download.eclipse.org/releases/mars \
#   -installIU net.sourceforge.shelled.feature.group \
#   "

- name: eclipse | Install Vrapper
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://vrapper.sourceforge.net/update-site/unstable,http://download.eclipse.org/releases/mars \
  -installIU net.sourceforge.vrapper.feature.group \
  -installIU net.sourceforge.vrapper.eclipse.jdt.feature.feature.group \
  -installIU net.sourceforge.vrapper.plugin.argtextobj.feature.group \
  -installIU net.sourceforge.vrapper.plugin.indenttextobj.feature.group \
  -installIU net.sourceforge.vrapper.plugin.linetextobj.feature.group \
  -installIU net.sourceforge.vrapper.plugin.methodtextobj.feature.group \
  -installIU net.sourceforge.vrapper.plugin.splitEditor.feature.group \
  -installIU net.sourceforge.vrapper.plugin.surround.feature.group \
  "

- name: eclipse | Install FindBugs
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://findbugs.cs.umd.edu/eclipse, \
  -installIU edu.umd.cs.findbugs.plugin.eclipse.feature.group \
  "

- name: eclipse | Install TM Terminal
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://download.eclipse.org/tm/terminal/marketplace, \
  -installIU org.eclipse.tm.terminal.feature.feature.group \
  "

- name: eclipse | Install PlantUML
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://basar.idi.ntnu.no/svn/tdt4100/anonymous/trunk/updatesite, \
  -installIU net.sourceforge.plantuml.feature.feature.group \
  "

- name: eclipse | Install PMD
  command: "eclipse -nosplash \
  -application org.eclipse.equinox.p2.director \
  -repository http://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site, \
  -installIU net.sourceforge.pmd.eclipse.feature.group \
  "

# - name: eclipse | Install Gradle IDE Pack
#   command: "eclipse -nosplash \
#   -application org.eclipse.equinox.p2.director \
#   -repository http://www.nodeclipse.org/updates/gradle-ide-pack, \
#   -installIU org.springsource.ide.eclipse.gradle.feature.feature.group \
#   "

