---

- name: upgrade all packages
  dnf: name=* state=latest
  tags: slow

- dnf: name={{ item }} state=latest
  with_items:
     - R # For https://github.com/hyiltiz/vim-plugins-profile
     - apvlv # pdf viewer
     - cadaver # WevDAV client
     - cmigemo
     - ctags
     - dconf-editor
     - devscripts-minimal # for checkbahisms
     - docker
     - eclipse
     - figlet
     - ftp
     - gcc
     - gftp # ftp client
     - gnome-tweak-tool
     - go
     - graphviz # for plantuml
     - gvim
     - hg # for ttyrec2gif
     - hub
     - ibus-mozc # required logout/login
     - key-mon # screen key input
     - libselinux-python # for ansible run
     - lshw # Hardware Lister
     - man-pages-ja
     - maven
     - community-mysql
     - nkf
     - npm
     - pandoc
     - patch
     - plantuml
     - python-devel
     - python-pip
     - pigz
     - ruby-devel
     - rubygems
     - shcov
     - shunit2
     - strace
     - sysstat
     - tmux
     - vim
     - w3m # for vim-plugin vim-ref
     - wine
     - xclip
     - xvkbd # for vim-plugin im_control.
     - xwd # for ttygif
     - ShellCheck
  tags: slow

- debug: msg="install chrome"
- copy: src=google-chrome.repo dest=/etc/yum.repos.d/ follow=yes
- dnf: name=google-chrome-stable state=latest

- debug: msg="install dropbox"
- copy: src=dropbox.repo dest=/etc/yum.repos.d/ follow=yes
- dnf: name=nautilus-dropbox state=latest
  tags: slow
- command: dropbox start -i
  become: no
  tags: manual

# - debug: msg="install insync"
# - copy: src=insync.repo dest=/etc/yum.repos.d/ follow=yes
# - rpm_key: state=present key=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
# - dnf: name=insync state=latest enablerepo=insync
#
# - debug: msg="install calibre"
# - copy: src=fedora-calibre.repo dest=/etc/yum.repos.d/ follow=yes
# - dnf: name=calibre state=latest enablerepo=fedora-calibre
#
# - debug: msg="install screenkey" # screen key input
# - command: which screenkey
#   register: has_screenkey
#   ignore_errors: yes
# - get_url: url=http://download.opensuse.org/repositories/home:Kenzy:packages/Fedora_{{ fedora_version }}/home:Kenzy:packages.repo dest=/etc/yum.repos.d/
#   when: has_screenkey.rc != 0
# - replace: dest=/etc/yum.repos.d/home:Kenzy:packages.repo regexp='enable=1' replace='enable=0'
# - dnf: name=screenkey state=latest enablerepo=home_Kenzy_packages
#
# - debug: msg="install playonlinux"
# - command: which playonlinux
#   register: has_playonlinux
#   ignore_errors: yes
#   become: no
# - get_url: url=http://rpm.playonlinux.com/playonlinux.repo dest=/etc/yum.repos.d/
#   when: has_playonlinux.rc != 0
# - replace: dest=/etc/yum.repos.d/playonlinux.repo regexp='enable=1' replace='enable=0'
# - dnf: name=playonlinux state=latest enablerepo=playonlinux

