---

- debug: msg="install ttygif"
- command: which ttygif
  register: has_ttygif
  ignore_errors: yes
  become: no
- block:
  - get_url: url=https://github.com/sugyan/ttygif/releases/download/0.0.1/ttygif_linux_amd64.tar.gz dest=/tmp
  - unarchive: src=/tmp/ttygif_linux_amd64.tar.gz dest={{ lib_dir }}
  - copy: src={{ lib_dir }}/ttygif_linux_amd64/ttygif dest={{ bin_dir }} mode=0755
  when: has_ttygif.rc != 0

- debug: msg="install winetricks"
- command: which winetricks
  register: has_winetricks
  ignore_errors: yes
  become: no
- get_url: url=http://www.kegel.com/wine/winetricks dest={{ bin_dir }} mode=0755
  when: has_winetricks.rc != 0

- debug: msg="install gibo"
- command: which gibo
  register: has_gibo
  ignore_errors: yes
  become: no
- get_url: url=https://raw.github.com/simonwhitaker/gibo/master/gibo dest={{ bin_dir }} mode=0755
  when: has_gibo.rc != 0

- debug: msg="install Todo.sh (todo.txt-cli)"
- command: which todo.sh
  register: has_todo
  ignore_errors: yes
  become: no
- block:
  - unarchive: src=https://github.com/ginatrapani/todo.txt-cli/releases/download/v2.10/todo.txt_cli-2.10.tar.gz dest={{ lib_dir }} copy=no
  - file: src={{ lib_dir }}/todo.txt_cli-2.10/todo.sh dest={{ bin_dir }}/todo.sh mode=0755 state=link
  - file: src={{ lib_dir }}/todo.txt_cli-2.10/todo_completion dest=/etc/bash_completion.d/todo_completion mode=0755 state=link
  - file: src=~/Dropbox/todo dest=~/Documents/todo mode=0755 state=link
    become: no
  when: has_todo.rc != 0

# TODO: Not working. https://github.com/github/hub/issues/1041
- get_url: url=https://raw.githubusercontent.com/github/hub/master/etc/hub.bash_completion.sh dest=/etc/bash_completion.d/hub.bash_completion.sh

