---
- hosts: localhost
  connection: local
  roles:
    # TODO 順序性を無くしたい.
    # TODO role単位での実行のためにtagsにrole名を記載するの冗長
    # TODO workaroundとして変数を定義している
    #
    # Caution: homeディレクトリの英語化を早めにやったほうがよい.
    # Caution: gnomeの設定を早めにやりたい(操作性)
    #
    - { role: gnome    , become: no  , tags: ["gnome"] }
    - { role: dnf      , become: yes , tags: ["dnf"] }
    - { role: manually , become: yes , tags: ["manually"] }
    - { role: make     , become: yes , tags: ["make"] }
    - { role: pms      , become: yes , tags: ["pms"] }
    - { role: npm      , become: yes , tags: ["npm"] }
    - { role: gem      , become: yes , tags: ["gem"] }
    - { role: golang   , become: no  , tags: ["golang"] }
    - { role: pip      , become: yes , tags: ["pip"] }
    - { role: git      , become: no  , tags: ["git"] }
    - { role: ghq      , become: no  , tags: ["ghq"] }
    - { role: vim      , become: no  , tags: ["vim"], hateblo_api_key: '' }
    - { role: eclipse  , become: no  , tags: ["eclipse", "slow"] }
    - { role: settings , become: no  , tags: ["settings"], wunderClientId: '', wunderAccessToken: '' }

