---

- hosts: localhost
  connection: local
  tasks:
    - shell: LANGUAGE=C LC_MESSAGES=C xdg-user-dirs-gtk-update
    # チェックしないと、IME切替時にxmodmapの設定がリセットされるっぽい(結局trueでもリセットされちゃうっぽい)
    - command: gsettings set org.freedesktop.ibus.general use-system-keyboard-layout true
    - command: gsettings set org.gnome.desktop.input-sources sources "[('ibus', 'mozc-jp'), ('xkb', 'jp')]"
    - command: gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
    - command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
    # これでビープ音を無効にできるが、「サウンド」-「音響効果」-「警告音の音量」は"オン"のまま.
    - command: gsettings set org.gnome.desktop.wm.preferences audible-bell false
    - command: gsettings set org.gnome.shell enabled-extensions "['background-logo@fedorahosted.org', 'alternate-tab@gnome-shell-extensions.gcampax.github.com']"
    - command: gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop', 'chromium-browser.desktop', 'gvim.desktop', 'eclipse.desktop', 'wine-Programs-Amazon-Amazon Kindle-Kindle.desktop']"
    - command: gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled false

    - command: gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    - command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name gnome-terminal
    - command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command gnome-terminal
    - command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding Launch1

    - copy: src=xmodmap.desktop dest=/home/oji/.config/autostart/ follow=yes

    # TODO キー設定インポートが自動化できてない
    - command: /usr/libexec/mozc/mozc_tool --mode=config_dialog
