---

- hosts: localhost
  connection: local
  vars_prompt:
    - name: "hateblo_api_key"
      prompt: "Please enter your hateblo-apikey. see http://blog.hatena.ne.jp/assout/assout.hatenablog.com/config/detail"
      private: no

  tasks:
    - git: repo=git@github.com:Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim

    - command: ~/.vim/bundle/neobundle.vim/bin/neoinstall

    - file: path=~/.cache/hateblo/blog state=directory

    - shell: echo "let g:hateblo_api_key='{{ hateblo_api_key }}'" > ~/.vimrc.local
      when: hateblo_api_key != ''
