---

- shell: go get -u {{ item }}
  with_items:
    - github.com/Songmu/ghg/cmd/ghg
    - github.com/simeji/jid/cmd/jid
    - github.com/yuroyoro/gommit-m

- command: ghg get {{ item }}
  with_items:
    - Songmu/ghch
    # - haya14busa/reviewdog # TODO fail
    - motemen/ghq
    - pranavraja/tldr
    # - tomnomnom/gron # TODO fail
- command: ghq root
  register: ghq_root

- command: ghq get -p {{ item }}
  with_items:
    - https://github.com/assout/lint-sandbox
    - https://github.com/assout/memolist.wiki
    - https://github.com/assout/remarkjs-sandbox
    - https://github.com/assout/scripts
    - https://github.com/assout/todo.txt-note
    - https://github.com/assout/todo.txt-p
    - https://github.com/chrisallenlane/cheat # For completion
    - https://github.com/chrismdp/p
    - https://github.com/timpulver/todo.txt-graph # For graph add-on.
    - https://github.com/tmux-plugins/tpm

- shell: "{{ ghq_root.stdout }}/github.com/assout/memolist.wiki/symlink.sh"

- debug: msg="Setup tmux plug-ins"
- file: path=~/.tmux/plugins/ state=directory
- file: src={{ ghq_root.stdout }}/github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm state=link

- file: path=~/.todo.actions.d/ state=directory
- file: src={{ ghq_root.stdout }}/github.com/timpulver/todo.txt-graph dest=~/.todo.actions.d/graph state=link
- file: src={{ ghq_root.stdout }}/github.com/assout/todo.txt-note/note dest=~/.todo.actions.d/note state=link
- file: src={{ ghq_root.stdout }}/github.com/assout/todo.txt-p/p dest=~/.todo.actions.d/p state=link


