---

- debug: msg="install ghq"
- command: which ghq
  register: has_ghq
  ignore_errors: yes
- get_url: url=https://github.com/motemen/ghq/releases/download/v0.7.4/ghq_linux_amd64.zip dest=/tmp
  when: has_ghq.rc != 0
- file: path={{ lib_dir }}/ghq state=directory
- unarchive: src=/tmp/ghq_linux_amd64.zip dest={{ lib_dir }}/ghq mode=0755
  when: has_ghq.rc != 0
- file: src={{ lib_dir }}/ghq/ghq dest={{ bin_dir }}/ghq mode=0755 state=link
  when: has_ghq.rc != 0

- command: ghq root
  register: ghq_root

- command: ghq get -p {{ item }}
  with_items:
    - https://github.com/assout/ansible-playbooks
    - https://github.com/assout/dotfiles
    - https://github.com/assout/lint-sandbox
    - https://github.com/assout/memolist.wiki
    - https://github.com/assout/remarkjs-sandbox
    - https://github.com/assout/scripts
    - https://github.com/assout/todo.txt-note
    - https://github.com/assout/todo.txt-p
    - https://github.com/aurelien-rainone/tmux-gitbar
    - https://github.com/chrismdp/p
    - https://github.com/timpulver/todo.txt-graph # For graph add-on.
    - https://github.com/tmux-plugins/tpm
    - https://github.com/yascentur/RictyDiminished

- shell: "{{ ghq_root.stdout }}/github.com/assout/dotfiles/symlink.sh"
- shell: "{{ ghq_root.stdout }}/github.com/assout/memolist.wiki/symlink.sh"

- copy: src={{ item }} dest=/usr/share/fonts/ force=no
  with_fileglob: "{{ ghq_root.stdout }}/github.com/yascentur/RictyDiminished/*.ttf"
  become: yes

- debug: msg="Setup tmux plug-ins"
- file: src={{ ghq_root.stdout }}/github.com/aurelien-rainone/tmux-gitbar dest=~/.tmux-gitbar state=link

- file: path=~/.tmux/plugins/ state=directory
- file: src={{ ghq_root.stdout }}/github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm state=link

- file: path=~/.todo.actions.d/ state=directory
- file: src={{ ghq_root.stdout }}/github.com/timpulver/todo.txt-graph dest=~/.todo.actions.d/graph state=link
- file: src={{ ghq_root.stdout }}/github.com/assout/todo.txt-note/note dest=~/.todo.actions.d/note state=link
- file: src={{ ghq_root.stdout }}/github.com/assout/todo.txt-p/p dest=~/.todo.actions.d/p state=link

