---

- debug: msg="install ghq"
- command: which ghq
  register: has_ghq
  ignore_errors: yes
- get_url: url=https://github.com/motemen/ghq/releases/download/v0.7.4/ghq_linux_amd64.zip dest=/tmp
  when: has_ghq.rc != 0
- file: path={{ lib_dir }}/ghq state=directory
- unarchive: src=/tmp/ghq_linux_amd64.zip dest={{ lib_dir }}/ghq mode=0755
  when: has_ghq.rc != 0
- file: src={{ lib_dir }}/ghq/ghq dest={{ bin_dir }}/ghq mode=0755 state=link
  when: has_ghq.rc != 0

- command: ghq root
  register: ghq_root

- debug: msg={{ ghq_root.stdout }}
- command: ghq get -p {{ item }}
  with_items:
    - https://github.com/assout/ansible-playbooks
    - https://github.com/assout/dotfiles
    - https://github.com/assout/memolist
    - https://github.com/assout/scripts
    - https://github.com/assout/lint-sandbox
    - https://github.com/assout/remarkjs-sandbox
    - https://github.com/aurelien-rainone/tmux-gitbar
    - https://github.com/tmux-plugins/tpm
    # TODO: notesファイル名をタスク名にしたい(grepするので)
    - https://github.com/mgarrido/todo.txt-cli
    - https://github.com/yascentur/RictyDiminished

- shell: "{{ ghq_root.stdout }}/github.com/assout/dotfiles/symlink.sh"
- shell: "{{ ghq_root.stdout }}/github.com/assout/memolist/symlink.sh"
- shell: "{{ ghq_root.stdout }}/github.com/assout/scripts/symlink.sh"

- shell: ln -sf {{ ghq_root.stdout }}/github.com/aurelien-rainone/tmux-gitbar ~/.tmux-gitbar
- shell: mkdir -p ~/.tmux/plugins && ln -sf {{ ghq_root.stdout }}/github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

- shell: cd {{ ghq_root.stdout }}/github.com/mgarrido/todo.txt-cli && git checkout note
- file: path={{ lib_dir }}/todo.actions.d/ state=directory
  become: yes
- file: src={{ ghq_root.stdout }}/github.com/mgarrido/todo.txt-cli/todo.actions.d/{{ item }} dest={{ lib_dir }}/todo.actions.d/{{ item }} state=link
  with_items:
    - archive
    - del
    - note
    - rm
  become: yes

- copy: src={{ item }} dest=/usr/share/fonts/ force=no
  with_fileglob: "{{ ghq_root.stdout }}/github.com/yascentur/RictyDiminished/*.ttf"
  become: yes
 
