---

# TODO git repo destでローカルの変更がうわがかれるのを阻止したい.
- hosts: localhost
  connection: local
  tasks:
    - command: ssh -T git@github.com
      register: exit
      failed_when: exit.rc not in [0, 1]

    - user: name=oji generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
      when : exit.rc not in [0, 1]

    - shell: cat /home/oji/ssh/id_rsa.pub | /usr/bin/xclip -sel clip
      when : exit.rc not in [0, 1]

    - pause: prompt="clipboard value to github.(https://github.com/settings/ssh)"
      when : exit.rc not in [0, 1]

    - command: ssh -T git@github.com
      register: exit
      failed_when: exit.rc not in [0, 1]

    - git: repo=git@github.com:assout/dotfiles.git
           version=master
           dest=/home/oji/Development/dotfiles
           update=no

    - command: /home/oji/Development/dotfiles/dotfilesLink.sh

    - git: repo=git@github.com:yascentur/RictyDiminished.git
           version=master
           dest=/home/oji/Development/RictyDiminished
           update=no

    - copy: src={{ item }}
            dest=/usr/share/fonts/
            force=no
      with_fileglob: /home/oji/Development/RictyDiminished/*.ttf
      sudo: yes

    - git: repo=git@github.com:assout/unite-todo.git
           version=master
           dest=/home/oji/Development/unite-todo
