---

- hosts: localhost
  connection: local
  vars_prompt:
    - name: "hateblo_api_key"
      prompt: "Please enter your hateblo-apikey. see http://blog.hatena.ne.jp/assout/assout.hatenablog.com/config/detail"
  tasks:
    - git: repo=git@github.com:Shougo/neobundle.vim version=master dest=~/.vim/bundle/neobundle.vim
    - command: ~/.vim/bundle/neobundle.vim/bin/neoinstall

    - file: path=~/.cache/hateblo/blog state=directory
    - shell: echo "let g:hateblo_api_key='{{ hateblo_api_key }}'" > ~/.vimrc.local
      when: hateblo_api_key != ''

    - get_url: url="http://www.namazu.org/~tsuchiya/sdic/data/gene95.tar.gz" dest=/tmp
    - file: path=~/.vim/dict state=directory
    - unarchive: src=/tmp/gene95.tar.gz dest=~/.vim/dict/
    - shell: nkf -Sw -Lu -m0 --in-place ~/.vim/dict/gene.txt

