---

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest disablerepo=fedora-chromium-stable,google-chrome

    - yum: name={{ item }} state=latest
      with_items:
        - yum-plugin-fastestmirror
        - apvlv
        - byobu
        - cadaver # WevDAV client
        - cmigemo
        - ctags
        - dconf-editor
        - eclipse
        - ftp
        - gcc
        - gftp
        - gnome-tweak-tool
        - go # for ttyrec2gif
        - gvim
        - hg # for ttyrec2gif
        - ibus-mozc # required logout/login
        - man-pages-ja
        - nkf
        - python-pip
        - vim
        - w3m # for vim-plugin vim-ref
        - wine
        - xclip
        - xvkbd # for vim-plugin im_control.
        - xwd # for ttygif

    - debug: msg="install dropbox"
    - copy: src=files/dropbox.repo dest=/etc/yum.repos.d/ follow=yes
    - yum: name=nautilus-dropbox state=latest enablerepo=Dropbox
    - command: dropbox

    - debug: msg="install insync"
    - copy: src=files/insync.repo dest=/etc/yum.repos.d/ follow=yes
    - rpm_key: state=present key=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
    - yum: name=insync state=latest enablerepo=insync

    - debug: msg="install calibre"
    - copy: src=files/fedora-calibre.repo dest=/etc/yum.repos.d/ follow=yes
    - yum: name=calibre state=latest enablerepo=fedora-calibre

    - debug: msg="install chormium"
    - command: which chromium-browser
      register: has_chromium
      ignore_errors: yes
    - get_url: url=http://repos.fedorapeople.org/repos/spot/chromium-stable/fedora-chromium-stable.repo dest=/etc/yum.repos.d/
      when: has_chromium.rc != 0
    - get_url: url=http://repos.fedorapeople.org/repos/spot/chromium-stable/spot.gpg dest=/etc/pki/rpm-gpg/spot.gpg
      when: has_chromium.rc != 0
    - yum: name=chromium state=latest

