---

- hosts: localhost
  connection: local
  sudo: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest disablerepo=fedora-chromium-stable,google-chrome

    - yum: name={{ item }} state=latest
      with_items:
        - yum-plugin-fastestmirror
        - byobu
        - dconf-editor
        - eclipse
        - ftp
        - gcc
        - gnome-tweak-tool
        - gvim
        # required logout/login
        - ibus-mozc
        - man-pages-ja
        - python-pip
        - vim
        - wine 
        - xclip
        # for vim-plugin im_control.
        - xvkbd

    - command: which vint
      register: has_vint
      ignore_errors: yes

    - command: pip install vim-vint
      when : has_vint.rc == 1

    - name: get chromium repo
      get_url: url=http://repos.fedorapeople.org/repos/spot/chromium-stable/fedora-chromium-stable.repo dest=/etc/yum.repos.d/

    - name: get chromium repo pgp
      get_url: url=http://repos.fedorapeople.org/repos/spot/chromium-stable/spot.gpg dest=/etc/pki/rpm-gpg/spot.gpg

    - yum: name=chromium state=latest

    - yum: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=present

    - copy: src=files/dropbox.repo dest=/etc/yum.repos.d/ follow=yes

    # required manual setup
    - yum: name=nautilus-dropbox state=latest enablerepo=Dropbox

    - command: dropbox

    - stat: path="/home/oji/.wine/drive_c/Program Files (x86)/Amazon/Kindle/Kindle.exe"
      register: has_kindle

    - name: get kindle for pc for wine
      get_url: url=http://www.amazon.co.jp/kindlepcdownload dest=/tmp
      when: has_kindle.stat.md5 is not defined

    - command: wine KindleForPC-installer.exe
      when: has_kindle.stat.md5 is not defined

    - name: Get latest peco version
      shell: curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'
      register: peco_latest_version

    - name: Download latest peco
      get_url: url=https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz dest=/tmp/peco_linux_amd64.tar.gz

    - name: Extract peco
      unarchive: src=/tmp/peco_linux_amd64.tar.gz dest=/tmp/

    - name: Copy to /usr/bin/
      copy: src=/tmp/peco_linux_amd64/peco dest=/usr/bin/ mode=0755

    - copy: src=files/fedora-calibre.repo dest=/etc/yum.repos.d/ follow=yes

    - yum: name=calibre state=latest enablerepo=fedora-calibre

    - copy: src=files/insync.repo dest=/etc/yum.repos.d/ follow=yes

    - rpm_key: state=present key=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key

    - yum: name=insync state=latest enablerepo=insync

