---

# TODO git repo destでローカルの変更がうわがかれるのを阻止したい.

- command: ssh -T git@github.com
  register: exit
  failed_when: exit.rc not in [0, 1, 255]

- user: name=oji generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  when : exit.rc not in [0, 1]

- shell: cat ~/.ssh/id_rsa.pub | /usr/bin/xclip -sel clip
  when : exit.rc not in [0, 1]

- pause: prompt="clipboard value to github.(https://github.com/settings/ssh)"
  when : exit.rc not in [0, 1]
  tags : manual

- debug: msg="install ghq"
- command: which ghq
  register: has_ghq
  ignore_errors: yes
  become: no
- get_url: url=https://github.com/motemen/ghq/releases/download/v0.7.4/ghq_linux_amd64.zip dest=/tmp
  when: has_ghq.rc != 0
- file: path={{ lib_dir }}/ghq state=directory
- unarchive: src=/tmp/ghq_linux_amd64.zip dest={{ lib_dir }}/ghq mode=0755
  when: has_ghq.rc != 0
- file: src={{ lib_dir }}/ghq/ghq dest={{ bin_dir }}/ghq mode=0755 state=link
  when: has_ghq.rc != 0

- command: ghq get --update {{ item }}
  with_items:
    - https://github.com/assout/dotfiles
    - https://github.com/assout/memolist
    - https://github.com/assout/scripts
    - https://github.com/assout/lint-sandbox
    - https://github.com/assout/remarkjs-sandbox

- shell: $(ghq root)/github.com/assout/dotfiles/install.sh

# TODO to ghq
# - git: repo=git@github.com:yascentur/RictyDiminished.git
#        version=master
#        dest={{ third_dir }}/RictyDiminished
#        update=no
#
# - copy: src={{ item }} dest=/usr/share/fonts/ force=no
#   with_fileglob: "{{ third_dir }}/RictyDiminished/*.ttf"
#   become: yes
#
# - shell: curl -L https://raw.githubusercontent.com/assout/dotfiles/master/install.sh | bash
#   tags:
#     - skip_ansible_lint
#
# - shell: curl -L https://raw.githubusercontent.com/assout/memolist/master/install.sh | bash
#   tags:
#     - skip_ansible_lint
#
# - debug: msg="install Todo.sh Add-ons - note"
#
# - file: path={{ lib_dir }}/todo.actions.d/ state=directory
# # TODO: うごかない@home
# - git: repo=git@github.com:metalelf0/pomodori-todo.txt
#        version=feature/linux-terminal-notifier
#        dest={{ third_dir }}/pomodori-todo.txt
#        update=no
# - file: src={{ third_dir }}/pomodori-todo.txt/pom dest={{ lib_dir }}/todo.actions.d/pom mode=0755 state=link
#
# # TODO: notesファイル名をタスク名にしたい(grepするので)
# - git: repo=git@github.com:mgarrido/todo.txt-cli
#        version=note
#        dest={{ third_dir }}/todo.txt-cli
#        update=no
# - file: src={{ third_dir }}/todo.txt-cli/todo.actions.d/archive dest={{ lib_dir }}/todo.actions.d/archive mode=0755 state=link
# - file: src={{ third_dir }}/todo.txt-cli/todo.actions.d/del dest={{ lib_dir }}/todo.actions.d/del mode=0755 state=link
# - file: src={{ third_dir }}/todo.txt-cli/todo.actions.d/note dest={{ lib_dir }}/todo.actions.d/note mode=0755 state=link
# - file: src={{ third_dir }}/todo.txt-cli/todo.actions.d/rm dest={{ lib_dir }}/todo.actions.d/rm mode=0755 state=link
#
