---

# TODO git repo destでローカルの変更がうわがかれるのを阻止したい.

- command: ssh -T git@github.com
  register: exit
  failed_when: exit.rc not in [0, 1, 255]

- user: name=oji generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  when : exit.rc not in [0, 1]

- shell: cat ~/.ssh/id_rsa.pub | /usr/bin/xclip -sel clip
  when : exit.rc not in [0, 1]

- pause: prompt="clipboard value to github.(https://github.com/settings/ssh)"
  when : exit.rc not in [0, 1]
  tags : manual

- command: ssh -T git@github.com
  register: exit
  failed_when: exit.rc not in [0, 1]
  tags : fail

- git: repo=git@github.com:yascentur/RictyDiminished.git
       version=master
       dest={{ thirdDir }}/RictyDiminished
       update=no

- copy: src={{ item }}
        dest=/usr/share/fonts/
        force=no
  with_fileglob: "{{ thirdDir }}/RictyDiminished/*.ttf"
  become: yes

- git: repo=git@github.com:assout/unite-todo.git
       version=master
       dest={{ vimDir }}/unite-todo
       update=no

- shell: curl -L https://raw.githubusercontent.com/assout/dotfiles/master/install.sh | bash
  tags:
    - skip_ansible_lint

- shell: curl -L https://raw.githubusercontent.com/assout/memolist/master/install.sh | bash
  tags:
    - skip_ansible_lint

