---

# TODO exec vim plug

# TODO roles内での指定方法
# - vars_prompt:
#   - name: "hateblo_api_key"
#     prompt: "Please enter your hateblo-apikey. see http://blog.hatena.ne.jp/assout/assout.hatenablog.com/config/detail"

- file: path=~/.vim/backup/ state=directory
- file: path=~/.cache/undo state=directory
- file: path=~/.vim/autoload/ state=directory
- get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim

- file: path=~/.cache/hateblo/blog state=directory
- stat: path="~/.vimrc.local"
  register: has_localrc
- shell: echo "let g:hateblo_api_key='{{ hateblo_api_key }}'" > ~/.vimrc.local
  when: has_localrc.stat.exists == False

- stat: path="~/.vim/dict/gene.txt"
  register: has_gene
- block:
  - file: path=~/.vim/dict state=directory
  - unarchive: src=http://www.namazu.org/~tsuchiya/sdic/data/gene95.tar.gz dest=~/.vim/dict/ copy=no
  - shell: nkf -Sw -Lu -m0 --in-place ~/.vim/dict/gene.txt
  when: has_gene.stat.exists == False


