---

# TODO roles内での指定方法
# - vars_prompt:
#   - name: "wunderClientId"
#     prompt: "wunderline client id (https://developer.wunderlist.com/apps/)"
#   - name: "wunderAccessToken"
#     prompt: "wunderline access token (https://developer.wunderlist.com/apps/)"

- debug: msg="setting wunderline"
- stat: path="~/.wunderlinerc"
  register: has_wunderline
- block:
  - copy: src=.wunderlinerc dest=/home/oji/ follow=yes
  - replace: dest=~/.wunderlinerc regexp='__clientId__' replace={{ wunderClientId }}
  - replace: dest=~/.wunderlinerc regexp='__accessToken__' replace={{ wunderAccessToken }}
  when: has_wunderline.stat.exists == False

